FROM geerlingguy/php-apache:latest

COPY . /var/www/html/.

RUN chmod -R 777 /var/www/html/PHPmailer
RUN chmod -R 777 /var/www/html/TCPDF
#RUN chmod -R 777 /var/www/html/admin/definitions
#RUN chmod -R 777 /var/www/html/admin/definitions/upload

COPY ./ports.conf /etc/apache2/ports.conf
COPY ./apache.conf /etc/apache2/site-enabled/000-default.conf